//! Generate `moq_iroh.h` from the exported functions. The committed copy in
//! `include/` is what hosts build against; a test fails when it is stale.

use std::env;
use std::path::PathBuf;

fn main() {
	println!("cargo:rerun-if-changed=src");
	let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
	let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("moq_iroh.h");
	let config = cbindgen::Config {
		header: Some(
			"/* moq-iroh-c: Media over QUIC between iroh endpoints. Generated by cbindgen from\n * rs/moq-iroh-c/src; do not edit. */"
				.into(),
		),
		pragma_once: true,
		documentation: true,
		cpp_compat: true,
		usize_is_size_t: true,
		..Default::default()
	};
	cbindgen::Builder::new()
		.with_crate(&crate_dir)
		.with_config(config)
		.with_language(cbindgen::Language::C)
		.generate()
		.expect("Unable to generate bindings")
		.write_to_file(&out);
}
