/* moq-iroh-c: Media over QUIC between iroh endpoints. Generated by cbindgen from
 * rs/moq-iroh-c/src; do not edit. */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A bad argument: a null or non-UTF-8 string, an unknown relay mode, a bad ticket.
 */
#define MOQI_ERR_ARG -1

/**
 * No such handle (or a handle of another kind).
 */
#define MOQI_ERR_HANDLE -2

/**
 * The buffer is too small; `moqi_object.len` (or the return of the stats call) says how big it must be.
 */
#define MOQI_ERR_SMALL -3

/**
 * The endpoint could not be bound, or a file could not be read or written.
 */
#define MOQI_ERR_IO -4

/**
 * The subscription has ended and everything it received has been read.
 */
#define MOQI_ERR_ENDED -5

/**
 * moq refused (a broadcast or track that cannot be created).
 */
#define MOQI_ERR_MOQ -6

/**
 * The library panicked inside the call; the reason is in `moqi_last_error`.
 */
#define MOQI_ERR_PANIC -7

/**
 * `moqi_object.flags`: the first object of its group.
 */
#define MOQI_OBJ_GROUP_START 1

/**
 * `moqi_object.flags`: groups were skipped (or one was cut short) before this object.
 */
#define MOQI_OBJ_GAP 2

/**
 * How a node is set up. Strings are UTF-8 and NUL-terminated; they are copied.
 */
typedef struct moqi_node_config {
  /**
   * The endpoint's secret key file (64 hex digits). Created, owner-only,
   * when missing, so the endpoint id stays the same across runs. NULL: a new
   * key (and id) every time.
   */
  const char *secret_path;
  /**
   * `"default"` (n0's public relays and address lookup), `"off"` (direct
   * paths only), or a relay URL (only that relay, no address lookup: peers
   * find each other through tickets). NULL means `"default"`.
   */
  const char *relay;
  /**
   * UDP port to bind on every IPv4 interface; 0 lets the system pick.
   */
  uint16_t port;
} moqi_node_config;

/**
 * One object of a subscribed track, as [`moqi_read`] hands it over.
 */
typedef struct moqi_object {
  /**
   * The moq group sequence number.
   */
  uint64_t group;
  /**
   * The object's index within its group (0 for the first).
   */
  uint64_t index;
  /**
   * The publisher's wall clock when it published the object, in microseconds since the Unix epoch.
   */
  uint64_t sent_us;
  /**
   * This host's wall clock when moq handed the object over, in microseconds since the Unix epoch.
   */
  uint64_t recv_us;
  /**
   * Payload bytes.
   */
  uint64_t len;
  /**
   * `MOQI_OBJ_*` bits.
   */
  uint32_t flags;
} moqi_object;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Bind an iroh endpoint and start serving its origin. Blocks while the socket
 * is bound (not while relays are reached). A node handle, or a negative error.
 */
int32_t moqi_node_new(const struct moqi_node_config *config);

/**
 * Close a node: its connections, publishers and subscriptions end.
 */
int32_t moqi_node_close(int32_t node);

/**
 * The node's ticket, `iroh://<endpoint id>?relay=<url>&addr=<ip:port>...`:
 * everything a peer needs to dial it. Its length, or `MOQI_ERR_SMALL` when
 * `cap` cannot hold it and its NUL (`moqi_last_error` says how much).
 */
int32_t moqi_node_ticket(int32_t node, char *buf, size_t cap);

/**
 * A JSON snapshot of the node for display (see the crate README for its
 * fields). Its length; `MOQI_ERR_SMALL` when `cap` is too small.
 */
int32_t moqi_stats(int32_t node, char *buf, size_t cap);

/**
 * Publish broadcast `broadcast` on `node` with one track, `track`. Peers that
 * connect to the node can subscribe to it. A publisher handle.
 */
int32_t moqi_publish(int32_t node, const char *broadcast, const char *track);

/**
 * Publish one object. `new_group` finishes the group in progress and starts
 * the next one with this object; a subscriber that joins or falls behind
 * starts at a group, so put a key frame there. The group's sequence number.
 */
int32_t moqi_publish_object(int32_t publisher, const uint8_t *data, size_t len, bool new_group);

/**
 * Stop publishing: the track and broadcast finish.
 */
int32_t moqi_publish_close(int32_t publisher);

/**
 * Dial the peer a ticket names (or a bare endpoint id) from `node` and
 * subscribe to `track` of its broadcast `broadcast`. Groups older than
 * `max_age_ms` behind the newest are skipped, not queued. Returns at once; the
 * connection is made in the background (`moqi_stats` shows how it goes).
 */
int32_t moqi_subscribe(int32_t node,
                       const char *ticket,
                       const char *broadcast,
                       const char *track,
                       uint32_t max_age_ms);

/**
 * Make a subscription read slowly on purpose: it waits `delay_ms` before it
 * takes each object from moq, so it falls behind the live edge and moq skips
 * groups for it. 0 reads at full speed again.
 */
int32_t moqi_subscribe_throttle(int32_t subscription, uint32_t delay_ms);

/**
 * Take the next object of a subscription: 1 and the object (its payload in
 * `buf`), 0 when none is waiting, `MOQI_ERR_SMALL` when `cap` is below
 * `out->len` (the object stays queued), `MOQI_ERR_ENDED` once the
 * subscription has ended and its queue is empty (`moqi_last_error` says why).
 */
int32_t moqi_read(int32_t subscription, struct moqi_object *out, uint8_t *buf, size_t cap);

/**
 * End a subscription and forget its handle.
 */
int32_t moqi_subscribe_close(int32_t subscription);

/**
 * A descriptor that becomes readable when an object or an ending is queued
 * for the host (POSIX); -1 where there is none (Windows: poll on a timer).
 * Reading is [`moqi_wake_clear`]'s job; the host only polls it.
 */
int32_t moqi_wake_fd(void);

/**
 * Empty the wake descriptor. Call before draining the queues, so a wake that
 * comes during the drain is not lost.
 */
void moqi_wake_clear(void);

/**
 * The reason for this thread's last negative return, NUL-terminated and cut
 * to fit `cap`. Its full length.
 */
int32_t moqi_last_error(char *buf, size_t cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
